### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by dariusf** [dariusf/iota#11]

**Comment by nwinter** [comment]
@dariusf what would be needed to support this? We could get a lot of beginner CodeCombat levels ready to go if we had them.

**Comment by dariusf** [comment]
It shouldn't take long -- I'll get on it.

**Comment by dariusf** [comment]
Okay, Io's `//` and `#` single-line comments and `/* ... */` (non-nesting) multiline comments are supported.

I noticed that the problem with methods being called twice has been resolved. Awesome!

**Comment by nwinter** [comment]
Thanks @dariusf!

Yeah, lots of improvements in Aether land, and if you'll notice, [CodeCombat's home page](http://codecombat.com/) is listing all the parsers as choices, including Io. It doesn't have much default code yet, but perhaps you can [help with that](https://github.com/codecombat/codecombat/issues/1229) a little, at least until we can see how to do some of the levels in Io?

**Comment by dariusf** [comment]
Sure, I'll be glad to help. I'm busy this week though, so I'll probably start over the weekend.
