### ISSUE TITLE
Aether cannot run headlessly with arguments due to iota.js

### ISSUE THREAD

**Issue by schmatz** [dariusf/iota#16]
If you run anything involving Aether from the command line with arguments, [iota.js](https://github.com/dariusf/iota/blob/master/iota.js#L9) tries to open whatever "file" the first argument lists.

Can you work around this behavior by perhaps making a separate test script?

**Comment by dariusf** [comment]
Okay, just fixed it (11e3a419ae605ba140cda7cfea89bc2362335480). Do tell me if there are any more issues.

**Comment by schmatz** [comment]
Awesome, thanks for the quick response!

On Thursday, June 5, 2014, Darius Foo notifications@github.com wrote:

> Closed #16 https://github.com/dariusf/iota/issues/16.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dariusf/iota/issues/16#event-128652544.

## 

Michael
